name: CI

# Alterar depois pra branch main
# on: pull_request

on:
  push:
    branches: [8-testar-workflow-ci-cd]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Config GitHub
        run: |
          git config --global user.email "${{secrets.GIT_USER_EMAIL}}"
          git config --global user.name "${{secrets.GIT_USER_NAME}}"

      # - name: Checkout Repository
      #   uses: actions/checkout@v3
  
      # NPM AUDIT
      # - name: run npm audit
      #   uses: oke-py/npm-audit-action@v2
      #   with:
      #     audit_level: low
      #     create_issues: true
      #     github_token: ${{ secrets.TOKEN_GIT }}
      #     issue_labels: vulnerability

      # Pensar se vamos manter
      # - name: Build
      #   run: docker-compose build 

      - name: Limpar Cache
        uses: actions/cache@v4
        with:
          path: ~/.npm # Substitua pelo caminho do cache que deseja limpar
          action: delete

      - name: install npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN_GIT }}
        run: npm ci

      # TruffleHog OSS (13k estrelas)
      # Action

      # GoSec Security Checker (7k estrelas)

      # Is WebSite Vulnerable (1.9k estrelas)

      # Stelligent CFN NAG (1.2k estrelas)

      # Snyk (500 estrelas)

      # Legitify Analize

      # Ferramentas SAST

      # SonarCloud Scan
      - name: SonarCloud
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Ferramentas SCA

      # OWASP DEPENDENCY CHECK (63 estrelas)
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'tcc-password-manager'
          path: './'
          format: 'HTML'
          out: 'reports'
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Upload Test results
        uses: actions/upload-artifact@v4
        with:
           name: Depcheck report
           path:  ${{github.workspace}}

      - name: Save Results
        if: always()
        run: |
          git clone "https://x-access-token:${{secrets.TOKEN_GIT}}@github.com/tcc-lucas-dafne/${{secrets.NAME_REPO_GIT}}" ${{secrets.NAME_REPO_GIT}}
          cd ${{secrets.NAME_REPO_GIT}}
          git checkout develop
          mkdir -p ${{secrets.NAME_REPO_GIT}}/reports
          cp -R ${{github.workspace}}/reports ${{secrets.NAME_REPO_GIT}}/reports
          git add .
          git commit -m "Adicionando relatório no repositório ${{ github.event.repository.name }} ${{ github.ref_name }}"
          git push origin develop
