name: CI

# Alterar depois pra branch main
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Pensar se vamos manter
      # - name: Container up
      #   run: docker-compose up -d

      - name: Config GitHub
        run: |
          git config --global user.email "${{secrets.GIT_USER_EMAIL}}"
          git config --global user.name "${{secrets.GIT_USER_NAME}}"
  
      # NPM AUDIT
      # - name: run npm audit
      #   uses: oke-py/npm-audit-action@v2
      #   with:
      #     audit_level: low
      #     create_issues: true
      #     github_token: ${{ secrets.TOKEN_GIT }}
      #     issue_labels: vulnerability

      - name: install dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN_GIT }}
        run: npm ci

      # TruffleHog OSS (13k estrelas)

      # GoSec Security Checker (7k estrelas)

      # Is WebSite Vulnerable (1.9k estrelas)

      # Stelligent CFN NAG (1.2k estrelas)

      # Snyk (500 estrelas)

      # Legitify Analize

      # Ferramentas SAST

      # SonarCloud Scan
      # - name: SonarCloud
      #   uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 0 
      
      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }} 
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      # - name: Checkout Repository
      #   uses: actions/checkout@v2

      # CHECKMARX (46 estrelas)
      # - uses: actions/checkout@v2
      # - name: Checkmarx CxFlow Action
      #   uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.9
      #   with:
      #     project: ${{ github.repository }}-PR
      #     team: ${{ secrets.CHECKMARX_TEAMS }}
      #     checkmarx_url: ${{ secrets.CHECKMARX_URL }}
      #     checkmarx_username: ${{ secrets.CHECKMARX_USERNAME }}
      #     checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }}
      #     checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
      #     scanners: sca
      #     break_build: true
      #     sca_api_url: ${{ secrets.SCA_API_URL }}
      #     sca_app_url: ${{ secrets.SCA_APP_URL }}
      #     sca_access_control_url: ${{ secrets.SCA_ACCESS_CONTROL_URL }}
      #     sca_tenant: ${{  secrets.SCA_TENANT }}
      #     sca_username: ${{ secrets.SCA_USERNAME }}

      # Ferramentas SCA

      # OWASP DEPENDENCY CHECK (63 estrelas)
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'tcc-password-manager'
          path: './'
          format: 'HTML'
          out: 'reports'
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Upload Test results
        uses: actions/upload-artifact@v4
        with:
           name: Depcheck report
           path:  ${{github.workspace}}/reports

      - name: Save Results
        if: always()
        run: |
          git clone "https://x-access-token:${{secrets.TOKEN_GIT}}@github.com/tcc-lucas-dafne/${{secrets.NAME_REPO_GIT}}" ${{secrets.NAME_REPO_GIT}}
          mkdir -p ${{secrets.NAME_REPO_GIT}}/reports
          cp -R ${{github.workspace}}/reports ${{secrets.NAME_REPO_GIT}}/reports
          cd ${{secrets.NAME_REPO_GIT}}
          git add .
          git commit -m "Adicionando relatório no repositório ${{ github.event.repository.name }} ${{ github.ref_name }}"
          git push