name: CI

on:
  push:
    branches: [8-testar-workflow-ci-cd]

jobs:
  eslint:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    
    # - name: install dependencies
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.TOKEN_GIT }}
    #   run: npm install

    # - name: ESLint check
    #   run: npx eslint ./src --ext .ts