name: Build and SAST Tests

on:
  pull_request:
    branches: [develop]

jobs:
  build_and_sca:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Config GitHub
        run: |
          git config --global user.email "${{secrets.GIT_USER_EMAIL}}"
          git config --global user.name "${{secrets.GIT_USER_NAME}}"

      - name: install npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN_GIT }}
        run: npm ci

      # SonarCloud Scan
      - name: SonarCloud
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      
      - name: SonarCloud Scan
        if: always()
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
