name: Password Manager CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Container up
        run: docker-compose up -d

      - name: Audit packages
        run: npm audit --audit-level moderate
        env:
          CI: true

      # TruffleHog OSS (13k estrelas)

      # GoSec Security Checker (7k estrelas)

      # Is WebSite Vulnerable (1.9k estrelas)

      # Stelligent CFN NAG (1.2k estrelas)

      # Snyk (500 estrelas)

      # Legitify Analize

      # SonarCloud Scan

      # CHECKMARX (46 estrelas)
      # - uses: actions/checkout@v2
      # - name: Checkmarx CxFlow Action
      #   uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.9
      #   with:
      #     project: ${{ github.repository }}-PR
      #     team: ${{ secrets.CHECKMARX_TEAMS }}
      #     checkmarx_url: ${{ secrets.CHECKMARX_URL }}
      #     checkmarx_username: ${{ secrets.CHECKMARX_USERNAME }}
      #     checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }}
      #     checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
      #     scanners: sca
      #     break_build: true
      #     sca_api_url: ${{ secrets.SCA_API_URL }}
      #     sca_app_url: ${{ secrets.SCA_APP_URL }}
      #     sca_access_control_url: ${{ secrets.SCA_ACCESS_CONTROL_URL }}
      #     sca_tenant: ${{  secrets.SCA_TENANT }}
      #     sca_username: ${{ secrets.SCA_USERNAME }}
  
      # OWASP DEPENDENCY CHECK (63 estrelas)
      - name: Checkout
        uses: actions/checkout@v2
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'tcc-password-manager'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@v4
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
      
      - name: Checkout
        uses: actions/checkout@v2
      - name: Move Test Results
        run: mv ${{github.workspace}}/reports ${{github.workspace}}/${{github.event.repository.name}}/reports

      # # ZAP (290 estrelas)
      # - name: Checkout
      #   uses: actions/checkout@v2
      # - name: ZAP Scan
      #   uses: zaproxy/action-baseline@v0.12.0
      #   with:
      #     token: ${{ secrets.TOKEN_GIT }}
      #     docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
      #     target: 'https://www.zaproxy.org'
      #     rules_file_name: '.zap/rules.tsv'
      #     cmd_options: '-a'
