name: Password Manager CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Container up
        run: docker-compose up -d

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3